# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjZX1LNNU_sC5edthkkaHKfH2iu0eTls
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import joblib
# import re
# import string
# 
# import nltk
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
# from nltk.stem import WordNetLemmatizer
# 
# 
# # Download required NLTK resources
# nltk.download("stopwords", quiet=True)
# nltk.download("punkt", quiet=True)
# nltk.download("punkt_tab", quiet=True)
# nltk.download("wordnet", quiet=True)
# 
# 
# # Load Model and TF-IDF
# model = joblib.load("sentiment_model.pkl")
# tfidf = joblib.load("tfidf_vectorizer.pkl")
# 
# 
# # Text Cleaning
# lemmatizer = WordNetLemmatizer()
# stop_words = set(stopwords.words("english"))
# 
# 
# def clean_text(text):
#     text = str(text).lower()
#     text = re.sub(r"http\S+|www\S+", " ", text)
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"[^\x00-\x7F]+", " ", text)
#     text = text.translate(str.maketrans("", "", string.punctuation))
#     text = re.sub(r"\d+", " ", text)
#     text = re.sub(r"\s+", " ", text).strip()
# 
#     tokens = word_tokenize(text)
#     tokens = [w for w in tokens if w not in stop_words and len(w) > 2]
#     tokens = [lemmatizer.lemmatize(w) for w in tokens]
# 
#     return " ".join(tokens)
# 
# 
# # Streamlit App
# st.title("Customer Review Sentiment Analysis")
# 
# st.write("Enter a customer review to predict its sentiment.")
# 
# 
# review = st.text_area("Enter your review:")
# 
# 
# if st.button("Predict Sentiment"):
# 
#     if review.strip() == "":
#         st.warning("Please enter a review.")
# 
#     else:
#         cleaned_review = clean_text(review)
# 
#         features = tfidf.transform([cleaned_review])
# 
#         prediction = model.predict(features)[0]
# 
#         st.success(f"Predicted Sentiment: {prediction}")

