# -*- coding: utf-8 -*-
"""StreamlitApp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zjZX1LNNU_sC5edthkkaHKfH2iu0eTls
"""

import streamlit as st
import pandas as pd
import numpy as np
import re
import string
from collections import Counter
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# --- Page Configuration ---
st.set_page_config(
    page_title="Customer Reviews EDA Dashboard",
    page_icon="📊",
    layout="wide"
)

# --- NLTK Resource Downloads ---
@st.cache_resource
def setup_nltk():
    nltk.download('punkt', quiet=True)
    nltk.download('punkt_tab', quiet=True)
    nltk.download('stopwords', quiet=True)
    nltk.download('wordnet', quiet=True)

setup_nltk()

# --- Data Loading & Caching ---
@st.cache_data
def load_data():
    # Reads the dataset file from the repository root
    return pd.read_excel('dataset.xlsx')

try:
    df_raw = load_data()
except Exception as e:
    st.error(f"Error loading 'dataset.xlsx'. Make sure it exists in the repository root directory. Error: {e}")
    st.stop()

# --- Preprocessing & Cleaning Function ---
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', ' ', text)               # URLs
    text = re.sub(r'<.*?>', ' ', text)                         # HTML tags
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)                 # Emojis / non-ASCII
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\d+', ' ', text)                           # Digits
    text = re.sub(r'\s+', ' ', text).strip()

    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words and len(w) > 2]
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    return ' '.join(tokens)

@st.cache_data
def preprocess_dataset(df):
    data = df.copy()
    data['title_char_len'] = data['title'].astype(str).apply(len)
    data['body_char_len'] = data['body'].astype(str).apply(len)
    data['body_word_count'] = data['body'].astype(str).apply(lambda x: len(x.split()))
    data['clean_body'] = data['body'].apply(clean_text)
    data = data[data['clean_body'].str.len() > 0].reset_index(drop=True)
    return data

with st.spinner("Processing text and preparing dataset..."):
    df = preprocess_dataset(df_raw)

# --- Sidebar Filters & Navigation ---
st.sidebar.title("Navigation & Filters")
rating_options = sorted(df['rating'].unique())
selected_ratings = st.sidebar.multiselect(
    "Filter by Rating:",
    options=rating_options,
    default=rating_options
)

filtered_df = df[df['rating'].isin(selected_ratings)]

# --- Main App Header ---
st.title("📊 Customer Reviews Exploratory Data Analysis")
st.markdown("Interactive dashboard exploring review ratings, length distributions, and key word frequencies.")

# --- Key Metrics Overview ---
col1, col2, col3, col4 = st.columns(4)
with col1:
    st.metric("Total Reviews Analyzed", len(filtered_df))
with col2:
    st.metric("Average Rating", f"{filtered_df['rating'].mean():.2f} ★")
with col3:
    st.metric("Avg Body Word Count", f"{filtered_df['body_word_count'].mean():.1f}")
with col4:
    st.metric("Avg Body Char Length", f"{filtered_df['body_char_len'].mean():.1f}")

st.divider()

# --- Section 1: Data Preview ---
st.subheader("1. Dataset Preview & Structural Info")
tab_data, tab_summary = st.tabs(["Raw & Cleaned Data", "Summary Statistics"])

with tab_data:
    st.dataframe(filtered_df[['title', 'rating', 'body', 'clean_body', 'body_word_count']].head(10), use_container_width=True)

with tab_summary:
    col_sum1, col_sum2 = st.columns(2)
    with col_sum1:
        st.write("**Dataset Shape:**", filtered_df.shape)
        st.write("**Missing Values:**")
        st.write(filtered_df.isnull().sum())
    with col_sum2:
        st.write("**Numerical Summary:**")
        st.dataframe(filtered_df[['rating', 'title_char_len', 'body_char_len', 'body_word_count']].describe().T)

st.divider()

# --- Section 2: Rating Distribution ---
st.subheader("2. Target Variable: Rating Distribution")
col_chart, col_pct = st.columns([2, 1])

with col_chart:
    fig_rating, ax_rating = plt.subplots(figsize=(7, 4))
    order = sorted(filtered_df['rating'].unique())
    sns.countplot(
        x='rating',
        hue='rating',
        data=filtered_df,
        palette='coolwarm',
        order=order,
        legend=False,
        ax=ax_rating
    )
    ax_rating.set_title('Distribution of Ratings', fontsize=12, fontweight='bold')
    ax_rating.set_xlabel('Rating')
    ax_rating.set_ylabel('Number of Reviews')
    st.pyplot(fig_rating)

with col_pct:
    st.write("**Rating Proportions:**")
    rating_pct = filtered_df['rating'].value_counts(normalize=True).sort_index().apply(lambda x: f"{x:.1%}")
    st.dataframe(pd.DataFrame({"Proportion": rating_pct}), use_container_width=True)

st.divider()

# --- Section 3: Text Length Analysis ---
st.subheader("3. Text Length Distribution")
fig_len, axes_len = plt.subplots(1, 2, figsize=(12, 4))
sns.histplot(filtered_df['body_char_len'], bins=40, kde=True, ax=axes_len[0], color='teal')
axes_len[0].set_title('Review Length in Characters')
axes_len[0].set_xlabel('Character Count')

sns.histplot(filtered_df['body_word_count'], bins=40, kde=True, ax=axes_len[1], color='coral')
axes_len[1].set_title('Review Length in Words')
axes_len[1].set_xlabel('Word Count')

plt.tight_layout()
st.pyplot(fig_len)

st.divider()

# --- Section 4: Word Frequency & Sentiment Comparison ---
st.subheader("4. Word Frequency Analysis")

all_words = ' '.join(filtered_df['clean_body']).split()
word_freq = Counter(all_words)

st.write(f"**Vocabulary Size (Filtered):** {len(word_freq)} unique words")

# Top 20 Overall
top20_df = pd.DataFrame(Counter(all_words).most_common(20), columns=['word', 'count'])
fig_top20, ax_top20 = plt.subplots(figsize=(8, 5))
sns.barplot(data=top20_df, x='count', y='word', hue='word', palette='mako', legend=False, ax=ax_top20)
ax_top20.set_title('Top 20 Most Frequent Words — Selected Reviews')
ax_top20.set_xlabel('Frequency')
ax_top20.set_ylabel('Word')
st.pyplot(fig_top20)

# Negative vs Positive Comparison
st.subheader("Top Words: Negative (1–2★) vs. Positive (4–5★)")

neg_text = ' '.join(df[df['rating'].isin([1, 2])]['clean_body'])
pos_text = ' '.join(df[df['rating'].isin([4, 5])]['clean_body'])

neg_df = pd.DataFrame(Counter(neg_text.split()).most_common(15), columns=['word', 'count'])
pos_df = pd.DataFrame(Counter(pos_text.split()).most_common(15), columns=['word', 'count'])

fig_compare, axes_compare = plt.subplots(1, 2, figsize=(14, 5))

sns.barplot(data=neg_df, x='count', y='word', hue='word', ax=axes_compare[0], palette='Reds_r', legend=False)
axes_compare[0].set_title('Top Words — Negative Reviews (1–2★)')
axes_compare[0].set_xlabel('Frequency')

sns.barplot(data=pos_df, x='count', y='word', hue='word', ax=axes_compare[1], palette='Greens_r', legend=False)
axes_compare[1].set_title('Top Words — Positive Reviews (4–5★)')
axes_compare[1].set_xlabel('Frequency')

plt.tight_layout()
st.pyplot(fig_compare)

