# -*- coding: utf-8 -*-
"""NLP PROJECT (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N5J_rZAd-P8E_ARb7oKTRVHQDA2zfGoX
"""

import pandas as pd
import numpy as np
import re
import string
from collections import Counter

import matplotlib.pyplot as plt
import seaborn as sns

"""## Load the dataset"""

df = pd.read_excel('dataset.xlsx')   # <-- update to your actual file path
df.head()

"""## Basic structural overview"""

print("Shape:", df.shape)
print("\nColumn names:", df.columns.tolist())
print("\nData types:\n", df.dtypes)
print("\nMissing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
df.describe(include='all').T

"""## Target variable: rating distribution"""

plt.figure(figsize=(8, 5))
order = sorted(df['rating'].unique())
ax = sns.countplot(x='rating', hue='rating', data=df, palette='coolwarm',
                    order=order, legend=False)
plt.title('Distribution of Ratings', fontsize=14, fontweight='bold')
plt.xlabel('Rating')
plt.ylabel('Number of Reviews')
# Formats directly as percentages (e.g., 31.5%)
print(df['rating'].value_counts(normalize=True).sort_index().apply(lambda x: f"{x:.1%}"))

"""## Text length analysis"""

df['title_char_len']  = df['title'].astype(str).apply(len)
df['body_char_len']   = df['body'].astype(str).apply(len)
df['body_word_count'] = df['body'].astype(str).apply(lambda x: len(x.split()))

fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.histplot(df['body_char_len'], bins=40, kde=True, ax=axes[0], color='teal')
axes[0].set_title('Review Length in Characters')
sns.histplot(df['body_word_count'], bins=40, kde=True, ax=axes[1], color='coral')
axes[1].set_title('Review Length in Words')
plt.tight_layout()
plt.show()

"""## Text cleaning"""

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import pos_tag


lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))


def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', ' ', text)               # URLs
    text = re.sub(r'<.*?>', ' ', text)                         # HTML tags
    text = re.sub(r'[^\x00-\x7F]+', ' ', text)                 # emojis / non-English scripts
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\d+', ' ', text)                           # numbers
    text = re.sub(r'\s+', ' ', text).strip()

    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words and len(w) > 2]
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    return ' '.join(tokens)

df['clean_body'] = df['body'].apply(clean_text)

# A few reviews are written almost entirely in Hindi script — after stripping
# non-ASCII characters they end up empty, so drop those:
df = df[df['clean_body'].str.len() > 0].reset_index(drop=True)
print("Shape after cleaning:", df.shape)

df[['body', 'clean_body']].head(10)

# 1. Overall Top 20 Most Frequent Words
all_words = ' '.join(df['clean_body']).split()
word_freq = Counter(all_words)
print("Vocabulary size:", len(word_freq))

# Convert top 20 to DataFrame for cleaner Seaborn plotting
top20_df = pd.DataFrame(word_freq.most_common(20), columns=['word', 'count'])

plt.figure(figsize=(10, 8))
sns.barplot(data=top20_df, x='count', y='word', hue='word', palette='mako', legend=False)
plt.title('Top 20 Most Frequent Words — All Reviews')
plt.xlabel('Frequency')
plt.ylabel('Word')
plt.show()

# 2. Top 15 Words for Negative vs Positive Reviews (Inline without def)
neg_text = ' '.join(df[df['rating'].isin([1, 2])]['clean_body'])
pos_text = ' '.join(df[df['rating'].isin([4, 5])]['clean_body'])

neg_df = pd.DataFrame(Counter(neg_text.split()).most_common(15), columns=['word', 'count'])
pos_df = pd.DataFrame(Counter(pos_text.split()).most_common(15), columns=['word', 'count'])

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

sns.barplot(data=neg_df, x='count', y='word', hue='word', ax=axes[0], palette='Reds_r', legend=False)
axes[0].set_title('Top Words — Negative Reviews (1–2★)')
axes[0].set_xlabel('Frequency')

sns.barplot(data=pos_df, x='count', y='word', hue='word', ax=axes[1], palette='Greens_r', legend=False)
axes[1].set_title('Top Words — Positive Reviews (4–5★)')
axes[1].set_xlabel('Frequency')

plt.tight_layout()
plt.show()

from wordcloud import WordCloud

wc_all = WordCloud(width=900, height=500, background_color='white',
                    colormap='viridis').generate(' '.join(df['clean_body']))
plt.figure(figsize=(12, 6))
plt.imshow(wc_all, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud — All Reviews', fontsize=14)
plt.show()

neg_text = ' '.join(df[df['rating'] <= 2]['clean_body'])
pos_text = ' '.join(df[df['rating'] >= 4]['clean_body'])
wc_neg = WordCloud(width=800, height=500, background_color='black', colormap='Reds').generate(neg_text)
wc_pos = WordCloud(width=800, height=500, background_color='black', colormap='Greens').generate(pos_text)

fig, axes = plt.subplots(1, 2, figsize=(16, 7))
axes[0].imshow(wc_neg, interpolation='bilinear'); axes[0].axis('off'); axes[0].set_title('Negative (1–2★)')
axes[1].imshow(wc_pos, interpolation='bilinear'); axes[1].axis('off'); axes[1].set_title('Positive (4–5★)')
plt.show()

df

"""## Model Building And Evaluation"""

# Create Sentiment Categories

def get_sentiment(rating):
    if rating <= 2:
        return "Negative"
    elif rating == 3:
        return "Neutral"
    else:
        return "Positive"

df["sentiment"] = df["rating"].apply(get_sentiment)

print(df["sentiment"].value_counts())

# Train-Test Split

from sklearn.model_selection import train_test_split

X_text = df["clean_body"]
y = df["sentiment"]

X_train_text, X_test_text, y_train, y_test = train_test_split(
    X_text,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data:", X_train_text.shape)
print("Testing Data:", X_test_text.shape)

# TF-IDF Feature Extraction

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X_train = tfidf.fit_transform(X_train_text)
X_test = tfidf.transform(X_test_text)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)

"""## Models For Training Testing"""

# Import Models

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

# Logistic Regression

lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)

lr_pred = lr_model.predict(X_test)

# Logistic Regression Evaluation

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, lr_pred))

print("\nClassification Report:")
print(classification_report(y_test, lr_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, lr_pred))

# Random Forest

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

# Random Forest Evaluation

print("Random Forest Accuracy:",
      accuracy_score(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

# Linear SVM

svm_model = LinearSVC()

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

# Linear SVM Evaluation

print("Linear SVM Accuracy:",
      accuracy_score(y_test, svm_pred))

print("\nClassification Report:")
print(classification_report(y_test, svm_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, svm_pred))

# Model Comparison

from sklearn.metrics import precision_score, recall_score, f1_score

results = {
    "Logistic Regression": [
        accuracy_score(y_test, lr_pred),
        precision_score(y_test, lr_pred, average="weighted"),
        recall_score(y_test, lr_pred, average="weighted"),
        f1_score(y_test, lr_pred, average="weighted")
    ],

    "Random Forest": [
        accuracy_score(y_test, rf_pred),
        precision_score(y_test, rf_pred, average="weighted"),
        recall_score(y_test, rf_pred, average="weighted"),
        f1_score(y_test, rf_pred, average="weighted")
    ],

    "Linear SVM": [
        accuracy_score(y_test, svm_pred),
        precision_score(y_test, svm_pred, average="weighted"),
        recall_score(y_test, svm_pred, average="weighted"),
        f1_score(y_test, svm_pred, average="weighted")
    ]
}

# Create Comparison Table

import pandas as pd

comparison = pd.DataFrame(
    results,
    index=["Accuracy", "Precision", "Recall", "F1 Score"]
).T

comparison

# Confusion Matrices

import matplotlib.pyplot as plt
import seaborn as sns

models = {
    "Logistic Regression": lr_pred,
    "Random Forest": rf_pred,
    "Linear SVM": svm_pred
}

for name, predictions in models.items():
    cm = confusion_matrix(y_test, predictions)

    plt.figure(figsize=(6, 4))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        xticklabels=["Negative", "Neutral", "Positive"],
        yticklabels=["Negative", "Neutral", "Positive"]
    )

    plt.title(f"{name} - Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

# Select Best Model

best_model_name = comparison["F1 Score"].idxmax()

print("Best Model:", best_model_name)
print("Best F1 Score:", comparison.loc[best_model_name, "F1 Score"])

# Get Best Model

if best_model_name == "Logistic Regression":
    best_model = lr_model

elif best_model_name == "Random Forest":
    best_model = rf_model

else:
    best_model = svm_model

print("Selected Model:", best_model_name)

# Save Model and TF-IDF Vectorizer

import joblib

joblib.dump(best_model, "sentiment_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model and TF-IDF vectorizer saved successfully.")

# Test Saved Model

loaded_model = joblib.load("sentiment_model.pkl")
loaded_tfidf = joblib.load("tfidf_vectorizer.pkl")

sample_review = ["This product is amazing and I really love it"]

sample_features = loaded_tfidf.transform(sample_review)

prediction = loaded_model.predict(sample_features)

print("Predicted Sentiment:", prediction[0])

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import joblib
# import re
# import string
# 
# import nltk
# from nltk.corpus import stopwords
# from nltk.tokenize import word_tokenize
# from nltk.stem import WordNetLemmatizer
# 
# 
# # Download required NLTK resources
# nltk.download("stopwords", quiet=True)
# nltk.download("punkt", quiet=True)
# nltk.download("punkt_tab", quiet=True)
# nltk.download("wordnet", quiet=True)
# 
# 
# # Load Model and TF-IDF
# model = joblib.load("sentiment_model.pkl")
# tfidf = joblib.load("tfidf_vectorizer.pkl")
# 
# 
# # Text Cleaning
# lemmatizer = WordNetLemmatizer()
# stop_words = set(stopwords.words("english"))
# 
# 
# def clean_text(text):
#     text = str(text).lower()
#     text = re.sub(r"http\S+|www\S+", " ", text)
#     text = re.sub(r"<.*?>", " ", text)
#     text = re.sub(r"[^\x00-\x7F]+", " ", text)
#     text = text.translate(str.maketrans("", "", string.punctuation))
#     text = re.sub(r"\d+", " ", text)
#     text = re.sub(r"\s+", " ", text).strip()
# 
#     tokens = word_tokenize(text)
#     tokens = [w for w in tokens if w not in stop_words and len(w) > 2]
#     tokens = [lemmatizer.lemmatize(w) for w in tokens]
# 
#     return " ".join(tokens)
# 
# 
# # Streamlit App
# st.title("Customer Review Sentiment Analysis")
# 
# st.write("Enter a customer review to predict its sentiment.")
# 
# 
# review = st.text_area("Enter your review:")
# 
# 
# if st.button("Predict Sentiment"):
# 
#     if review.strip() == "":
#         st.warning("Please enter a review.")
# 
#     else:
#         cleaned_review = clean_text(review)
# 
#         features = tfidf.transform([cleaned_review])
# 
#         prediction = model.predict(features)[0]
# 
#         st.success(f"Predicted Sentiment: {prediction}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# 
# streamlit
# scikit-learn
# joblib
# nltk

